### ISSUE TITLE
Issue if there is already a manifest-namespace defined in my cluster

### ISSUE THREAD

**Issue by badaldavda8** [aws-samples/cdk-eks-karpenter#106]
Hi team,

I have a cluster already created. I am attempting to add karpenter into it using this library - v0.0.30

I am getting an issue where it says - 
There is already a construct with 'manifest-namespace' in Cluster

Is there a way I can resolve this?

**Comment by badaldavda8** [comment]
<img width="667" alt="Screenshot 2023-06-06 at 5 39 42 PM" src="https://github.com/aws-samples/cdk-eks-karpenter/assets/45222001/d6d7958c-28f3-4113-9258-9e2805688161">

**Comment by andskli** [comment]
Closed by #107
