### ISSUE TITLE
no matches for kind "CronJob" in v ersion "batch/v1beta1"\n'

### ISSUE THREAD

**Issue by badaldavdatcpl** [aws-samples/cdk-eks-karpenter#91]
Tried deploying with the following - 

"""
        karpenter = Karpenter(self, "karpenter", cluster=cluster)

        provisioner_spec = {
        'requirements': [{
            'key': 'karpenter.sh/capacity-type',
            'operator': 'In',
            'values': ['spot']
        }],
        'limits': {
            'resources': {
            'cpu': 20
            }
        },
        'provider': {
            'subnetSelector': {
            'Name': 'PublicSubnet*'
            },
            'securityGroupSelector': {
            'aws:eks:cluster-name': cluster.cluster_name
            
            }
        }
        }

        karpenter.add_provisioner('spot-provisioner',provisioner_spec=provisioner_spec)
"""

Received response status [FAILED] from custom resource. Message returned: Error: b'con
figmap/aws-auth configured\nerror: error retrieving RESTMappings to prune: invalid res
ource batch/v1beta1, Kind=CronJob, Namespaced=true: no matches for kind "CronJob" in v
ersion "batch/v1beta1"\n'

Logs: /aws/lambda/MyEksBlueprintStack-awscdkawseksKu-Handler886CB40B-ni5iL3nrGKLh

at invokeUserFunction (/var/task/framework.js:102:19)
at processTicksAndRejections (internal/process/task_queues.js:95:5)
at async onEvent (/var/task/framework.js:22:27)

Kubernetes v1.25
cdk-eks-karpenter>=0.0.27 
aws-cdk-lib==2.73.0

**Comment by andskli** [comment]
I also stumbled across [your issue](https://github.com/aws/aws-cdk/issues/25027) in the CDK repo, which contains more complete example. FWIW I believe that https://github.com/aws/aws-cdk/issues/24580 reflects your issue.

Could you try specifying the @aws-cdk/lambda-layer-kubectl-vXX as described in [this comment](https://github.com/aws/aws-cdk/issues/24580#issuecomment-1466397526)? The integration test for this repository does that to mitigate similar issue, see [here](https://github.com/aws-samples/cdk-eks-karpenter/blob/main/test/integ.karpenter.ts#L1) and [here](https://github.com/aws-samples/cdk-eks-karpenter/blob/main/test/integ.karpenter.ts#L32).

**Comment by badaldavdatcpl** [comment]
Yes. That seems to be a likely issue, I will try out the documented approaches. Thanks for prompt response on this.

Closing this since its not related to cdk-eks-karpenter
