### ISSUE TITLE
Adding Label selectors / tolerations to the Karpenter deployment.

### ISSUE THREAD

**Issue by deepu-james** [aws-samples/cdk-eks-karpenter#99]
When using this library, is there a way to specify label selectors or tolerations for the Karpenter deployments that are getting created?
It is suitable to have only Karpenter pods installed in the nodes created when EKS is bootstrapped. I can add labels or taints to these nodes. But I haven't found a way to specify label selectors or tolerations for the Karpenter pods.

**Comment by andskli** [comment]
Closed by https://github.com/aws-samples/cdk-eks-karpenter/pull/100
